version: '3'

services:
  load_balancer:
    image: nginx
    ports:
      - "81:81"
      - "443:443"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  
    depends_on:
      - flask1
      - flask2
      - flask3
      - flask4
      - flask5
      - db
    networks:
      - flask_network

  flask1:
    <<: &flask
      image: python:3.9-slim
      command: sh -c "pip install Flask psycopg2-binary && python /code/app.py"
      ports:
        - "5000:5000"
      volumes:
        - ./flask_app:/code
      networks:
        - flask_network

  flask2:
    <<: *flask
    ports:
      - "5001:5000"

  flask3:
    <<: *flask
    ports:
      - "5002:5000"

  flask4:
    <<: *flask
    ports:
      - "5003:5000"

  flask5:
    <<: *flask
    ports:
      - "5004:5000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: your_username
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge











